---

- include: vars.yml
  tags:
    - system
    - sudo
    - vars
    - sudo-vars

- include: install.yml
  tags:
    - system
    - sudo
    - install
    - sudo-install

- include: config.yml
  tags:
    - system
    - sudo
    - config
    - sudo-config
